openapi: 3.0.3
info:
  title: Чат - OpenAPI 3.0
  description: сервис обмена сообщениями
  contact:
    email: safonoval@ya.ru
  version: 1.0.1
servers:
  - url: https://localhost
tags:
  - name: chatMessage
    description: Операции с сообщениями
  - name: chatUser
    description: Операции с пользователями
paths:
  /message/getChatMessage/{messageId}:
    get:
      tags:
        - chatMessage
      summary: Получить сообщения по ид
      description: Returns a single chatMessage
      operationId: getChatMessage
      parameters:
        - name: messageId
          in: path
          description: ID of chatMessage to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageRq'
        '404':
          description: chatMessage not found
  /message/getChatMessages:
    get:
      tags:
        - chatMessage
      summary:  Получить все сообщения
      description: Получить все сообщения
      operationId: getChatMessages
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatMessageRq'
  /message/getChatMessagesAfterDate/{datestart}:
    get:
      tags:
        - chatMessage
      summary: Получить все сообщения после даты
      description: Получить все сообщения после даты
      operationId: getChatMessagesAfterDate
      parameters:
        - name: datestart
          in: path
          description: ID of chatMessage to return
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatMessageRq'
  /message/addChatMessage:
    post:
      tags:
        - chatMessage
      summary: Отправить сообщение
      description: Отправить сообщение
      operationId: addChatMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRq'
      responses:
        '200':
          description: successful operation
          content:
            application/text:
              schema:
                type: string
                example: "3edb44ee-4d6e-4194-a61d-7f7d6caf48d3"
        '405':
          description: Invalid input
  /message/removeChatMessage:
    post:
      tags:
        - chatMessage
      summary: Удалить сообщение
      description: Удалить сообщение
      operationId: removeChatMessage
      requestBody:
        content:
          application/text:
            schema:
              type: string
              example: "3edb44ee-4d6e-4194-a61d-7f7d6caf48d3"
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  /message/removeAllChatMessages:
    post:
      tags:
        - chatMessage
      summary: Удалить все сообщения
      description: Удалить все сообщения
      operationId: removeAllChatMessages
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  /user/getChatUser/{userId}:
    get:
      tags:
        - chatUser
      summary: Получить пользователя по ид
      description: Returns a single chatMessage
      operationId: getChatUser
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatUserRq'
        '400':
          description: Invalid ID supplied
        '404':
          description: chatMessage not found
  /user/getChatUsers:
    get:
      tags:
        - chatUser
      summary:  Получить всех пользователей
      description: Получить всех пользователей
      operationId: getChatUsers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatUserRq'
        '400':
          description: Invalid status value
  /user/addChatUser:
    post:
      tags:
        - chatUser
      summary: Отправить сообщение
      description: Отправить сообщение
      operationId: addChatUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatUserRq'
      responses:
        '200':
          description: successful operation
          content:
            application/text:
              schema:
                type: string
                example: "3edb44ee-4d6e-4194-a61d-7f7d6caf48d3"
        '405':
          description: Invalid input
  /user/removeChatUser:
    post:
      tags:
        - chatUser
      summary: Удалить сообщение
      description: Удалить сообщение
      operationId: removeChatUser
      requestBody:
        content:
          application/text:
            schema:
              type: string
              example: "3edb44ee-4d6e-4194-a61d-7f7d6caf48d3"
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  /user/removeAllChatUsers:
    post:
      tags:
        - chatUser
      summary: Удалить все сообщения
      description: Удалить все сообщения
      operationId: removeAllChatUsers
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
components:
  schemas:
    ChatMessageRq:
      type: object
      required: [id, userId, dateTime]
      properties:
        id:
          type: string
          format: uuid
          example: '3edb44ee-4d6e-4194-a61d-7f7d6caf48d3'
        userId:
          type: string
          format: uuid
          example: '456744ee-4d6e-4194-a61d-7f7d6caf9876'
        dateTime:
          type: string
          format: date-time
        text:
          type: string
          example: 'Всем привет!'
      xml:
        name: сhatMessage
    ChatUserRq:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
          format: uuid
          example: '080944ee-4d6e-4194-a61d-7f7d6caf3215'
        name:
          type: string
          description: Никнейм
          example: Дядя Ваня
        active:
          type: boolean
      xml:
        name: сhatUser
  requestBodies:
    ChatMessage:
      description: ChatMessage object that needs to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChatMessageRq'
